export const CARDS_DATA = [
    {
        id: 0,
        name: 'buffalo_card',
        imagePath: 'https://i.ibb.co/4Zyt8yR/buffalo-card.png',
        emptyImagePath: 'https://i.ibb.co/Jsznnmg/empty-card.png',
        currentImagePath: 'https://i.ibb.co/Jsznnmg/empty-card.png',
    },
    {
        id: 1,
        name: 'desert_fennec_fox_card',
        imagePath: 'https://i.ibb.co/G7bPZKD/desert-fennec-fox-card.png',
        emptyImagePath: 'https://i.ibb.co/Jsznnmg/empty-card.png',
        currentImagePath: 'https://i.ibb.co/Jsznnmg/empty-card.png-card.png',
    },
    {
        id: 2,
        name: 'duck_card',
        imagePath: 'https://i.ibb.co/Y05XH1K/duck-card.png',
        emptyImagePath: 'https://i.ibb.co/Jsznnmg/empty-card.png',
        currentImagePath: 'https://i.ibb.co/Jsznnmg/empty-card.png',
    },
    {
        id: 3,
        name: 'kangaroo_card',
        imagePath: 'https://i.ibb.co/KGPXL5W/kangaroo-card.png',
        emptyImagePath: 'https://i.ibb.co/Jsznnmg/empty-card.png',
        currentImagePath: 'https://i.ibb.co/Jsznnmg/empty-card.png',
    },
    {
        id: 4,
        name: 'leopard_card',
        imagePath: 'https://i.ibb.co/jGYcQ1v/leopard-card.png',
        emptyImagePath: 'https://i.ibb.co/Jsznnmg/empty-card.png',
        currentImagePath: 'https://i.ibb.co/Jsznnmg/empty-card.png',
    },
    {
        id: 5,
        name: 'lion_card',
        imagePath: 'https://i.ibb.co/x1Vqykv/lion-card.png',
        emptyImagePath: 'https://i.ibb.co/Jsznnmg/empty-card.png',
        currentImagePath: 'https://i.ibb.co/Jsznnmg/empty-card.png',
    },
    {
        id: 6,
        name: 'raccoon_card',
        imagePath: 'https://i.ibb.co/7v0dKRK/raccoon-card.png',
        emptyImagePath: 'https://i.ibb.co/Jsznnmg/empty-card.png',
        currentImagePath: 'https://i.ibb.co/Jsznnmg/empty-card.png',
    },
    {
        id: 7,
        name: 'red_bear_card',
        imagePath: 'https://i.ibb.co/qgjMjNJ/red-bear-card.png',
        emptyImagePath: 'https://i.ibb.co/Jsznnmg/empty-card.png',
        currentImagePath: 'https://i.ibb.co/Jsznnmg/empty-card.png.png',
    },
    {
        id: 8,
        name: 'tiger_card',
        imagePath: 'https://i.ibb.co/NTnjGSn/tiger-card.png',
        emptyImagePath: 'https://i.ibb.co/Jsznnmg/empty-card.png',
        currentImagePath: 'https://i.ibb.co/Jsznnmg/empty-card.png',
    },
    {
        id: 9,
        name: 'zebra_card',
        imagePath: 'https://i.ibb.co/jk1GDHg/zebra-card.png',
        emptyImagePath: 'https://i.ibb.co/Jsznnmg/empty-card.png',
        currentImagePath: 'https://i.ibb.co/Jsznnmg/empty-card.png',
    }
];
